version: '3.1'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/pgsql_init:/docker-entrypoint-initdb.d
      - ./scripts/data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password 
      PGADMIN_LISTEN_PORT: 8001
    ports: 
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  postgres-data: